import Head from "next/head";
import { Inter } from "next/font/google";
import { GetServerSideProps } from "next";
import { useRouter } from "next/router";

import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps: GetServerSideProps = async ({
  res,
  draftMode = false,
}) => {
  if (draftMode) {
    res.setHeader("Vercel-CDN-Cache-Control", "max-age=0, no-cache");
  } else {
    res.setHeader("Vercel-CDN-Cache-Control", "max-age=60");
  }

  return {
    props: {},
  };
};

export default function Home() {
  const router = useRouter();
  const isDraftMode = router.isPreview; // why is there no `isDraftMode` in router?

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Draft Mode caching bug reproduction</h1>
        <p>
          Draft Mode is <strong>{isDraftMode ? "ON" : "OFF"}</strong>
        </p>
        {isDraftMode ? (
          <Link
            href="/api/draft/clear"
            prefetch={false}
            className={styles.link}
          >
            Exit draft mode
          </Link>
        ) : (
          <Link href="/api/draft" prefetch={false} className={styles.link}>
            Enter draft mode
          </Link>
        )}
      </main>
    </>
  );
}
